# Generated by Django 3.2.9 on 2022-01-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=200)),
                ('price', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('quantity', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinestore.login')),
            ],
        ),
        migrations.CreateModel(
            name='ordertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('date', models.DateField()),
                ('price', models.BigIntegerField()),
                ('cakeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinestore.addart')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinestore.signup')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacks', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinestore.signup')),
            ],
        ),
        migrations.CreateModel(
            name='complient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complients', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinestore.signup')),
            ],
        ),
    ]
