# Generated by Django 3.2.9 on 2022-01-21 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0002_usermessege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertable',
            old_name='cakeid',
            new_name='prdtid',
        ),
        migrations.CreateModel(
            name='carttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('prdt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinestore.addart')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinestore.signup')),
            ],
        ),
    ]
