# Generated by Django 3.2.9 on 2022-01-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0003_auto_20220121_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carttable',
            old_name='quantity',
            new_name='quanity',
        ),
    ]
