# Generated by Django 3.2.9 on 2022-01-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0004_rename_quantity_carttable_quanity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinestore.carttable'),
        ),
    ]
