# Generated by Django 3.2.9 on 2022-01-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0005_alter_ordertable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttable',
            name='sprice',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
